- hosts: localhost
  tasks:
    - name: Loading Config
      include_vars: config.yml
    - name: Provision
      ec2:
        id: "{{ provision_token }}"
        region: "{{ region }}"
        key_name: "{{ key }}"
        group_id: "{{ security_groups }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        wait_timeout: 350
        count: 3
        vpc_subnet_id: "{{ subnet }}"
        instance_tags: "{{ tags }}"
      register: ec2
    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 timeout=320 state=started
      with_items: ec2.instances
